/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastaneprojesi;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mert
 */
public class DoktorEkrani extends javax.swing.JDialog {
    DefaultTableModel model;
    Hastaİslemleri islemler1=new Hastaİslemleri();
    
    
    
    

    /**
     * Creates new form DoktorEkrani
     */
    public DoktorEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel) doktor_tablosu.getModel();
        doktor_goruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doktor_tablosu = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cinsiyet_alani = new javax.swing.JComboBox<>();
        tc_alani = new javax.swing.JTextField();
        adsoyad_alani = new javax.swing.JTextField();
        yas_alani = new javax.swing.JTextField();
        maas1_alani = new javax.swing.JTextField();
        doktorEkle = new javax.swing.JButton();
        doktorGuncelle = new javax.swing.JButton();
        doktor_sil = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        soyad_alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bolum_alani = new javax.swing.JComboBox<>();
        unvan_alani = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(620, 240, 240, 240));

        doktor_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "tc", "ünvanı", "ad", "soyad", "bolum", "yaşı", "cinsiyet", "maaş"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doktor_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktor_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doktor_tablosu);
        if (doktor_tablosu.getColumnModel().getColumnCount() > 0) {
            doktor_tablosu.getColumnModel().getColumn(0).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(1).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(2).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(3).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(4).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(5).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(6).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(7).setResizable(false);
            doktor_tablosu.getColumnModel().getColumn(8).setResizable(false);
        }

        arama_cubugu.setText("Arama Yap");
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Tc:");

        jLabel2.setText("Ünvan:");

        jLabel3.setText("Ad:");

        jLabel4.setText("Yaş:");

        jLabel5.setText("Cinsiyet");

        jLabel6.setText("Maaş:");

        cinsiyet_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Bayan" }));
        cinsiyet_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinsiyet_alaniActionPerformed(evt);
            }
        });

        doktorEkle.setText("Doktor Ekle");
        doktorEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorEkleActionPerformed(evt);
            }
        });

        doktorGuncelle.setText("Doktor Güncelle");
        doktorGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorGuncelleActionPerformed(evt);
            }
        });

        doktor_sil.setText("Doktor Sil");
        doktor_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktor_silActionPerformed(evt);
            }
        });

        jLabel7.setText("Soyad:");

        jLabel8.setText("Bolum:");

        bolum_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kalp ve Damar Hastalıkları", "Cildiye Hastalıkları", "Beyin ve Sinir Hastalıkları", "Göz Hastalıkları", "Kulak Burun Boğaz  Hastalıkları" }));

        unvan_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pratisyen", "Uzman", "Operatör", "Doçent", "Profesör" }));

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(doktor_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(yas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(doktorEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(doktorGuncelle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cinsiyet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(maas1_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(unvan_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(adsoyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(doktor_sil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(yas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(doktorEkle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(doktorGuncelle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(cinsiyet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(maas1_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(unvan_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(adsoyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(mesaj_yazisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        // TODO add your handling code here:
        
        
        String ara=arama_cubugu.getText();
        dinamikAra(ara);
        
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void cinsiyet_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinsiyet_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinsiyet_alaniActionPerformed

    private void doktorEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorEkleActionPerformed
        // TODO add your handling code here:
        Hastaİslemleri islemler =new Hastaİslemleri();
        mesaj_yazisi.setText("");
        String tc=tc_alani.getText();
        String unvan=unvan_alani.getSelectedItem().toString();
        String ad=adsoyad_alani.getText();
        String soyad=soyad_alani.getText();
        String bolum=bolum_alani.getSelectedItem().toString();
        String yas=yas_alani.getText();
        String cinsiyet=cinsiyet_alani.getSelectedItem().toString();
        String maas=maas1_alani.getText();
        
        islemler.doktor_Ekle(tc,unvan,ad,soyad,bolum,yas,cinsiyet,maas);
        doktor_goruntule();
        mesaj_yazisi.setText("Yeni Doktor Başarıyla Eklendi...");
      
        
    }//GEN-LAST:event_doktorEkleActionPerformed

    private void doktor_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktor_tablosuMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) doktor_tablosu.getModel();
        int secili_row = doktor_tablosu.getSelectedRow();
        
        tc_alani.setText(model.getValueAt(secili_row,1).toString());
        unvan_alani.setSelectedItem(model.getValueAt(secili_row,2).toString());
        adsoyad_alani.setText(model.getValueAt(secili_row,3).toString());
      soyad_alani.setText(model.getValueAt(secili_row,4).toString());
        bolum_alani.setSelectedItem(model.getValueAt(secili_row,5).toString());
        yas_alani.setText(model.getValueAt(secili_row,6).toString());
        cinsiyet_alani.setSelectedItem(model.getValueAt(secili_row,7).toString());
        maas1_alani.setText(model.getValueAt(secili_row,8).toString());
        
        
      
        
    }//GEN-LAST:event_doktor_tablosuMouseClicked

    private void doktorGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorGuncelleActionPerformed
        // TODO add your handling code here:
        Hastaİslemleri islem=new Hastaİslemleri();
        String tc=tc_alani.getText();
        String unvan=unvan_alani.getSelectedItem().toString();
        String ad=adsoyad_alani.getText();
        String soyad=soyad_alani.getText();
        String bolum=bolum_alani.getSelectedItem().toString();
        String yas=yas_alani.getText();
        String cinsiyet=cinsiyet_alani.getSelectedItem().toString();
        String maas=maas1_alani.getText();
        
        
         int selectedrow = doktor_tablosu.getSelectedRow();
         
         if (selectedrow == -1) {
            
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışanlar Tablosu şu anda boş. ");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir çalışan seçin.");
            }
        }
        else {
            
           
            int id = (int)model.getValueAt(selectedrow,0);
            
             islem.doktor_Guncelle(id,tc,unvan,ad,soyad,bolum,yas,cinsiyet,maas);
            
            doktor_goruntule();
            
            mesaj_yazisi.setText("Çalışan başarıyla güncellendi...");
        }
    }//GEN-LAST:event_doktorGuncelleActionPerformed

    private void doktor_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktor_silActionPerformed
        // TODO add your handling code here:
        Hastaİslemleri islem=new Hastaİslemleri();
        
            mesaj_yazisi.setText("");
        
        DefaultTableModel model = (DefaultTableModel) doktor_tablosu.getModel();
        
        int secili_row = doktor_tablosu.getSelectedRow();
        
        if (secili_row == -1) {
            if (doktor_tablosu.getRowCount() == 0 ) {
                
                mesaj_yazisi.setText( "Hasta bilgileri şu anda boş...");
            }
            else {
                
                mesaj_yazisi.setText("Lütfen silinecek bir kişi seçin...");
            }
        }
        else {
            int id=(int)model.getValueAt(secili_row,0);
            islem.doktor_Sil(id);
            model.removeRow(secili_row);
            
            mesaj_yazisi.setText("Kişi başarıyla silindi...");
        }
    }//GEN-LAST:event_doktor_silActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AnaEkran ekran=new AnaEkran();
            setVisible(false);
            ekran.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void dinamikAra(String ara) {
        
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
         doktor_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoktorEkrani dialog = new DoktorEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void doktor_goruntule() {
        //çalışan tablosu herseferinde 0'lanır
        model.setRowCount(0);
        
        ArrayList<Calisan> calisanlar1 = new ArrayList<Calisan>();
        
        
        
        calisanlar1 = islemler1.doktorlarıGetir();
        
        if (calisanlar1 != null ) {
            
            for (Calisan calisan : calisanlar1) {
                Object[] eklenecek = {calisan.getId(),calisan.getTc(),calisan.getUnvan() ,calisan.getAd(),calisan.getSoyad()
                        ,calisan.getBolum(),calisan.getYas(),calisan.getCinsiyet(),calisan.getMaas()};
                
                model.addRow(eklenecek);
                
                
                
            }
            
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adsoyad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JComboBox<String> bolum_alani;
    private javax.swing.JComboBox<String> cinsiyet_alani;
    private javax.swing.JButton doktorEkle;
    private javax.swing.JButton doktorGuncelle;
    private javax.swing.JButton doktor_sil;
    private javax.swing.JTable doktor_tablosu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maas1_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JComboBox<String> unvan_alani;
    private javax.swing.JTextField yas_alani;
    // End of variables declaration//GEN-END:variables

    
}
