package hastaneprojesi;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class HastaEkrani extends javax.swing.JDialog {
    DefaultTableModel model;
    Hastaİslemleri islemler =  new Hastaİslemleri();
    
    
    /**
     * Creates new form CalisanEkrani
     */
    public HastaEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) calisan_tablosu.getModel();
        hasta_goruntule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        calisan_tablosu = new javax.swing.JTable();
        tc_ara = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        calisanekle = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tc_alani = new javax.swing.JTextField();
        bolum_alani = new javax.swing.JComboBox<>();
        doktor_alani = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        randevusaat_alani = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));
        setBounds(new java.awt.Rectangle(680, 240, 0, 0));

        calisan_tablosu.setBackground(new java.awt.Color(153, 153, 255));
        calisan_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "soyad", "tc", "Doktor", "Randevu saati", "Bolum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calisan_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisan_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(calisan_tablosu);
        if (calisan_tablosu.getColumnModel().getColumnCount() > 0) {
            calisan_tablosu.getColumnModel().getColumn(0).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(1).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(2).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(3).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(4).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(5).setResizable(false);
            calisan_tablosu.getColumnModel().getColumn(6).setResizable(false);
        }

        tc_ara.setBackground(new java.awt.Color(204, 204, 255));
        tc_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_araActionPerformed(evt);
            }
        });
        tc_ara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tc_araKeyReleased(evt);
            }
        });

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("Polikinlik:");

        jLabel4.setText("Doktor:");

        ad_alani.setBackground(new java.awt.Color(204, 204, 255));

        soyad_alani.setBackground(new java.awt.Color(204, 204, 255));
        soyad_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyad_alaniActionPerformed(evt);
            }
        });

        mesaj_yazisi.setBackground(new java.awt.Color(255, 255, 255));
        mesaj_yazisi.setForeground(new java.awt.Color(204, 0, 0));

        calisanekle.setBackground(new java.awt.Color(153, 153, 255));
        calisanekle.setText("Randevu Al");
        calisanekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanekleActionPerformed(evt);
            }
        });

        guncelle.setBackground(new java.awt.Color(153, 153, 255));
        guncelle.setText("Randevu Guncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setBackground(new java.awt.Color(153, 153, 255));
        sil.setText("Randevu Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jLabel5.setText("Tc:");

        tc_alani.setBackground(new java.awt.Color(204, 204, 255));
        tc_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_alaniActionPerformed(evt);
            }
        });

        bolum_alani.setBackground(new java.awt.Color(204, 204, 255));
        bolum_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kalp ve Damar Hastalıkları ", "Kulak Burun Boğaz  Hastalıkları", "Beyin ve Sinir Hastalıkları", "Göz Hastalıkları", "Cildiye Hastalıkları" }));
        bolum_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum_alaniActionPerformed(evt);
            }
        });

        doktor_alani.setBackground(new java.awt.Color(204, 204, 255));
        doktor_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktor_alaniActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Randevu saati:");

        randevusaat_alani.setBackground(new java.awt.Color(204, 204, 255));
        randevusaat_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:30-10:00", "10:00-10:30", "10:30-11:00", "11:30-12:00" }));
        randevusaat_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randevusaat_alaniActionPerformed(evt);
            }
        });

        jLabel10.setText("Ara:");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Sistem Çıkış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(tc_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tc_alani)
                            .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(randevusaat_alani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doktor_alani, 0, 211, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calisanekle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calisanekle)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(doktor_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(tc_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randevusaat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void tc_ara_1(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        calisan_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
        
    }
    private void tc_araKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tc_araKeyReleased
        String ara = tc_ara.getText();
        
        tc_ara_1(ara);
        
        
        
    }//GEN-LAST:event_tc_araKeyReleased

    private void calisanekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanekleActionPerformed
        mesaj_yazisi.setText("");
        
        String ad  =  ad_alani.getText();
        String soyad = soyad_alani.getText();
        String  tc=tc_alani.getText();
        String doktor_adi = doktor_alani.getSelectedItem().toString();
        String randevu_saati=randevusaat_alani.getSelectedItem().toString();
     
        String bolum=bolum_alani.getSelectedItem().toString();
        
        islemler.hasta_Ekle(ad, soyad, tc, doktor_adi, randevu_saati, bolum);
        hasta_goruntule();
        mesaj_yazisi.setText("Yeni Çalışan Başarıyla Eklendi...");
      
        
       
        
        // bu kodlar ilede çalışan eklenebilir!
       // islemler.calisanEkle(ad,soyad,tc,doktor_adi,randevu_saati,bolum);
       /*
       if(ad_alani.getText().trim().equals("")){
                String message="ad kısmını doldurunuz";
                JOptionPane.showMessageDialog(this,message);
            }
            else{
                Object[] eklenecek = {ad,soyad,tc,doktor_adi,randevu_saati,bolum};
                model.addRow(eklenecek);
            }
        
        */
        
       // mesaj_yazisi.setText("Yeni Çalışan Başarıyla Eklendi...");
     /*  mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) calisan_tablosu.getModel();
        
        if (ad_alani.getText().trim().equals("")) {
            
            mesaj_yazisi.setText("isim boş bırakılamaz...");
        }
        else {
            
            
            Object[] eklenecek = {ad_alani.getText(),soyad_alani.getText(),tc_alani.getText(),doktor_alani.getSelectedItem().toString(),randevusaat_alani.getSelectedItem().toString(),bolum_alani.getSelectedItem().toString()};
            
            model.addRow(eklenecek);
            
        }
        */
        
        
        
    }//GEN-LAST:event_calisanekleActionPerformed

    private void calisan_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisan_tablosuMouseClicked
      DefaultTableModel model = (DefaultTableModel) calisan_tablosu.getModel();
        
        int secili_row = calisan_tablosu.getSelectedRow();
        
        ad_alani.setText(model.getValueAt(secili_row,1).toString());
        soyad_alani.setText(model.getValueAt(secili_row,2).toString());
        tc_alani.setText(model.getValueAt(secili_row,3).toString());
        doktor_alani.setSelectedItem(model.getValueAt(secili_row,4).toString());
        randevusaat_alani.setSelectedItem(model.getValueAt(secili_row,5).toString());
        bolum_alani.setSelectedItem(model.getValueAt(secili_row,6).toString());
        
     
     
        
        
    }//GEN-LAST:event_calisan_tablosuMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
      
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String tc=tc_alani.getText();
        String doktor_adi=doktor_alani.getSelectedItem().toString();
        String randevu_saati=randevusaat_alani.getSelectedItem().toString();
        String bolum=bolum_alani.getSelectedItem().toString();
        
        
        
        
        int selectedrow = calisan_tablosu.getSelectedRow();
        
        if (selectedrow == -1) {
            
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışanlar Tablosu şu anda boş. ");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir çalışan seçin.");
            }
        }
        else {
            
            
            
            
            int id = (int)model.getValueAt(selectedrow,0);
            
            
            
            
            
            islemler.hasta_Guncelle(id, ad, soyad, tc, doktor_adi, randevu_saati, bolum);
            
            hasta_goruntule();
            
            mesaj_yazisi.setText("Çalışan başarıyla güncellendi...");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
         Hastaİslemleri islem=new Hastaİslemleri();
        
            mesaj_yazisi.setText("");
        
        DefaultTableModel model = (DefaultTableModel) calisan_tablosu.getModel();
        
        int secili_row = calisan_tablosu.getSelectedRow();
        
        if (secili_row == -1) {
            if (calisan_tablosu.getRowCount() == 0 ) {
                
                mesaj_yazisi.setText( "Hasta bilgileri şu anda boş...");
            }
            else {
                
                mesaj_yazisi.setText("Lütfen silinecek bir kişi seçin...");
            }
        }
        else {
            int id=(int)model.getValueAt(secili_row,0);
            islem.hasta_Sil(id);
            model.removeRow(secili_row);
            
            mesaj_yazisi.setText("Kişi başarıyla silindi...");
        }
        
        
    }//GEN-LAST:event_silActionPerformed

    
          public void doktorveriGoruntule(String x){
          Hastaİslemleri islemler=new Hastaİslemleri();
      //  model.setRowCount(0);
        ArrayList<Calisan> doktorlar=new ArrayList<Calisan>();
        doktorlar =islemler.doktorlarıGetir();
       // String a="Kalp ve Damar Hastalıkları";
      //  String b="Beyin ve Sinir Hastalıkları";
        if(doktorlar !=null){

            for(int i=0;i<doktorlar.size();i++){
                Calisan calisan=doktorlar.get(i);
             if(calisan.getBolum().equals(x))   {

             doktor_alani.addItem(calisan.getUnvan()+" "+calisan.getAd()+" "+calisan.getSoyad());
             }
           // else if(calisan.getBolum().equals(a)){
           // email_alani.addItem(calisan.getUnvan()+calisan.getAd()+calisan.getSoyad());
           //  }
            }
        }
      }
    private void bolum_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum_alaniActionPerformed
        // TODO add your handling code here:
       Hastaİslemleri islem=new Hastaİslemleri();
       
         String a= bolum_alani.getSelectedItem().toString();
         
             ArrayList<Calisan> doktorlar=new ArrayList<Calisan>();
        doktorlar =islemler.doktorlarıGetir();
         
         if(a.equalsIgnoreCase("Kalp ve Damar Hastalıkları ")){
             
             
           //  String[] doktor_adi={"Dr.Nuri Cenk","Dr.Fatma Esenkaya","Dr.Rıfat Şahin","Uzm.Dr.Fatih Niyazoğlu"};
            //doktor_alani.setModel(new javax.swing.DefaultComboBoxModel<>(doktor_adi));
            
            doktor_alani.removeAllItems();
            doktorveriGoruntule("Kalp ve Damar Hastalıkları");
             }
             else if(a.equalsIgnoreCase("Cildiye Hastalıkları")){
                // String[] doktor_adi2={"Dr. Emre Sungur","Dr Berkay Bayrak","Dr Sena Gül","Mahmut Şentürk"};
                 //doktor_alani.setModel(new javax.swing.DefaultComboBoxModel<>(doktor_adi2));
                  doktor_alani.removeAllItems();
            doktorveriGoruntule("Cildiye Hastalıkları");
                 
             }
             else if(a.equalsIgnoreCase("Beyin ve Sinir Hastalıkları")){
              //   String[] doktor_adi3 = {"Dr Elif Suna","Dr Ömer Cihat","Prof.Dr Ceren İme"};
                // doktor_alani.setModel(new javax.swing.DefaultComboBoxModel<>(doktor_adi3));
                   doktor_alani.removeAllItems();
            doktorveriGoruntule("Beyin ve Sinir Hastalıkları");
            }
             else if(a.equalsIgnoreCase("Göz Hastalıkları")){
                 //String[] doktor_adi4 = {"Dr Hasan Garip","Uzm Dr Suna Uçan","Prof.Dr Kenan Tas"};
                 //doktor_alani.setModel(new javax.swing.DefaultComboBoxModel<>(doktor_adi4));
                       doktor_alani.removeAllItems();
            doktorveriGoruntule("Göz Hastalıkları");
                 
             }
         else if(a.equalsIgnoreCase("Kulak Burun Boğaz  Hastalıkları")){
                // String[] doktor_adi5 = {"Dr Esma Çakır","Uzm Dr Figen Karadeniz","Prof.Dr.Mert Mısırlı"};
                 //doktor_alani.setModel(new javax.swing.DefaultComboBoxModel<>(doktor_adi5));
                    doktor_alani.removeAllItems();
            doktorveriGoruntule("Kulak Burun Boğaz  Hastalıkları");
                 
                 
         } 
         for (int i=0;i<doktorlar.size();i++){
             doktor_alani.addItem(doktorlar.get(i).getAd());
 
         }
         
         
         
         /*Kalp ve Damar Hastalıkları 
Kulak Burun Boğaz  Hastalıkları
Beyin ve Sinir Hastalıkları
Göz Hastalıkları*/
    }//GEN-LAST:event_bolum_alaniActionPerformed

    private void randevusaat_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randevusaat_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randevusaat_alaniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tc_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_araActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AnaEkran ekran=new AnaEkran();
            setVisible(false);
            ekran.setVisible(true);
      
        
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void soyad_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyad_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyad_alaniActionPerformed

    private void tc_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_alaniActionPerformed

    private void doktor_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktor_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktor_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void hasta_goruntule() {
        //çalışan tablosu herseferinde 0'lanır
        model.setRowCount(0);
        
        ArrayList<Hastane_Bilgi> calisanlar = new ArrayList<Hastane_Bilgi>();
        
        
        
        calisanlar = islemler.calisanlariGetir();
        
        if (calisanlar != null ) {
            
            for (Hastane_Bilgi calisan : calisanlar) {
                Object[] eklenecek = {calisan.getId(),calisan.getAd(),calisan.getSoyad(),calisan.getTc(),calisan.getDoktor_adi(),calisan.getRandevu_saati(),calisan.getBolum()};
                
                model.addRow(eklenecek);
                
                
                
            }
            
        }
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HastaEkrani dialog = new HastaEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JComboBox<String> bolum_alani;
    private javax.swing.JTable calisan_tablosu;
    private javax.swing.JButton calisanekle;
    private javax.swing.JComboBox<String> doktor_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JComboBox<String> randevusaat_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField tc_ara;
    // End of variables declaration//GEN-END:variables
}
