/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastaneprojesi;

import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class kayitekrani extends javax.swing.JFrame {

    /**
     * Creates new form kayitekrani
     */
    public kayitekrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelkullanıcıadi = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        labelkayit = new javax.swing.JLabel();
        labelsifre = new javax.swing.JPasswordField();
        labelkayitbutonu = new javax.swing.JButton();
        labelkayitbutonu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));
        setBounds(new java.awt.Rectangle(680, 240, 0, 0));

        label.setBackground(new java.awt.Color(0, 255, 255));
        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setText("Kullanıcı Adı :");

        labelkayit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelkayit.setForeground(new java.awt.Color(255, 0, 0));
        labelkayit.setText("Parola:");

        labelkayitbutonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelkayitbutonu.setForeground(new java.awt.Color(255, 0, 0));
        labelkayitbutonu.setText("Kayit Ol");
        labelkayitbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelkayitbutonuActionPerformed(evt);
            }
        });

        labelkayitbutonu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelkayitbutonu1.setForeground(new java.awt.Color(255, 0, 0));
        labelkayitbutonu1.setText("Giris Paneline Dön");
        labelkayitbutonu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelkayitbutonu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelkayitbutonu1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastaneprojesi/icon1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(labelkullanıcıadi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(labelkayit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelkayitbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labelkayitbutonu1))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(labelkullanıcıadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelkayit))
                    .addComponent(labelsifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelkayitbutonu)
                    .addComponent(labelkayitbutonu1))
                .addGap(28, 28, 28)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelkayitbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelkayitbutonuActionPerformed
      
        Hastaİslemleri islemler=new Hastaİslemleri();
        String kullanici_adi=labelkullanıcıadi.getText();
        String sifre=new String(labelsifre.getPassword());
        
        islemler.kayitEkle1(kullanici_adi,sifre);
        mesaj_yazisi.setText("Yeni Kayıt Başarıyla Eklendi...");
        
        ArrayList<KayitKullanici> user_list = GirisEkrani.getListe_kayit();
        
        user_list.add(new KayitKullanici(labelkullanıcıadi.getText(),new String(labelsifre.getPassword())));
        
        
        
        
        
    }//GEN-LAST:event_labelkayitbutonuActionPerformed

    private void labelkayitbutonu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelkayitbutonu1ActionPerformed
        // TODO add your handling code here:
        GirisEkrani giris_ekrani=new GirisEkrani();
        giris_ekrani.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_labelkayitbutonu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelkayit;
    private javax.swing.JButton labelkayitbutonu;
    private javax.swing.JButton labelkayitbutonu1;
    private javax.swing.JTextField labelkullanıcıadi;
    private javax.swing.JPasswordField labelsifre;
    private javax.swing.JLabel mesaj_yazisi;
    // End of variables declaration//GEN-END:variables
}
